mod = angular.module('adminr-md-layout')

mod.controller('AppCtrl', ($scope, $timeout, $mdSidenav, $log) ->

  ###*
  # Supplies a function that will continue to operate until the
  # time is up.
  ###

  debounce = (func, wait, context) ->
    timer = undefined
    ->
      `var context`
      context = $scope
      args = Array::slice.call(arguments)
      $timeout.cancel timer
      timer = $timeout((->
        timer = undefined
        func.apply context, args
        return
      ), wait or 10)
      return

  ###*
  # Build handler to open/close a SideNav; when animation finishes
  # report completion in console
  ###

  buildDelayedToggler = (navID) ->
    debounce (->
      $mdSidenav(navID).toggle().then ->
        $log.debug 'toggle ' + navID + ' is done'
        return
      return
    ), 200

  buildToggler = (navID) ->
    ->
      $mdSidenav(navID).toggle().then ->
        $log.debug 'toggle ' + navID + ' is done'
        return
      return

  $scope.toggleLeft = buildDelayedToggler('left')
  $scope.toggleRight = buildToggler('right')

  $scope.isOpenRight = ->
    $mdSidenav('right').isOpen()

  return
).controller('LeftCtrl', ($scope, $timeout, $mdSidenav, $log) ->

  $scope.close = ->
    $mdSidenav('left').close().then ->
      $log.debug 'close LEFT is done'
      return
    return

  return
).controller 'RightCtrl', ($scope, $timeout, $mdSidenav, $log) ->

  $scope.close = ->
    $mdSidenav('right').close().then ->
      $log.debug 'close RIGHT is done'
      return
    return

  return

# ---
# generated by js2coffee 2.1.0